got rid of most bugs
jedouard98/codeu_summer_2017 pull request #23
Opened 2017-07-22 11:12 UTC by kac320

2017-07-31 19:35 UTC, turtlefarmer requested changes

2017-07-31 19:35 UTC, turtlefarmer commented on src/codeu/chat/common/User.java
> +  // // User A wants to follow User B
delete unused code instead of commenting out.

2017-07-31 19:35 UTC, turtlefarmer commented on src/codeu/chat/common/User.java
> +    System.out.println("HERE! -------------------------" + followees.size());
Either delete or cleanup debugging code.

2017-07-31 19:35 UTC, turtlefarmer commented on src/codeu/chat/server/Model.java
> +    // User user1 = userById().first(userA.id);
delete commented out code.

2017-08-01 22:39 UTC, kac320 commented on src/codeu/chat/common/User.java
> +    System.out.println("HERE! -------------------------" + followees.size());
not quite sure what you mean here. which lines should I delete?

2017-08-01 22:42 UTC, kac320 commented on src/codeu/chat/server/Model.java
> +    // User user1 = userById().first(userA.id);
done

2017-08-01 23:13 UTC, turtlefarmer commented
Please resolve conflicts and I'll take another look.

2017-08-01 23:28 UTC, merged