updated tests
jedouard98/codeu_summer_2017 pull request #25
Opened 2017-07-22 11:13 UTC by kac320

2017-07-31 19:32 UTC, turtlefarmer requested changes

2017-07-31 19:32 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +    assertFalse("ERROR: Failed to follow user");
assertFalse takes a condition, not an error string.  You need to be asserting that the follow relationship was correctly created.

2017-08-01 22:55 UTC, kac320 commented
Changed the tests but not sure if I changed them for the better.

2017-08-01 23:13 UTC, turtlefarmer approved these changes
looks good.  :)

2017-08-01 23:21 UTC, merged