Kate
jedouard98/codeu_summer_2017 pull request #3
Opened 2017-06-06 02:59 UTC by kac320

Creates basic tests for Jessica's version of getVersion, getUptime, and Tokenizer.

2017-06-07 00:48 UTC, turtlefarmer requested changes

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +    private Model model;
Please standardize formatting with https://github.com/google/styleguide
There should be plugins you can install for your IDE.  The easiest way to format is just use the plugin's auto-format.

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertEquals("1.1", str);
This is too specific to the current version. I would just do a not null or empty type check.

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertFalse("ERROR: Exception during call on server. Check log for details.", model == null);
If you want to assert this, assert it before model.Version().   This will never assert to false or else the above will give a null pointer exception.

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertFalse("Response from server failed.", model == null);
No reason to assert for the same thing 3 times

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertNotEquals(0.0, model.Uptime());
if uptime is long, assert it against a long.  
Also, provide a message for asserts in case of failure.

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertNotEquals(0.0, model.Uptime());
Also, this can technically return 0.  I'd assert that it's a non-negative number.

2017-06-07 00:48 UTC, turtlefarmer commented on test/codeu/chat/server/BasicControllerTest.java
> +        assertFalse(t1.hasNext());
I'd add some more test cases with unescaped " or \

2017-06-17 16:53 UTC, kac320 commented
Edits have been made

2017-06-20 23:38 UTC, merged